version: "2"
services:
  admin-notificaciones:
    environment:
    - DB_USER=milito
    - DB_PASS=lautaro
    - DB_URL=159.89.87.78:27017
    - ML_CLIENT_ID=3659532861516182
    - ML_CLIENT_SECRET=EezWxXN7ip0Jd55Gvyp4Vn7xU0phnrxh
    - URL_ACTUAL=https://notiml.com
    - DB_NAME=mercadolibre
    container_name: admin-notificaciones
    image: admin-notificaciones
    restart: always
    ports:
      - "82:8080"
      - "9005:9005"

